const oRows = [
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
    {
        tid: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        Type:"null",
        Country:"Pak",
       OurCost: "5555",
        Deposit:"666",
        Sold:"7676",
        Balance:"abc",
        Reference:"xyz",
        CO:"null",
        CT:"null",
    },
   

]
export default oRows ;

       