
const oRows = [
    {
        id: "1",
        Pax_Name: "@MUI",
        Contact: "0000020",
        PNR: "22",
        GSD_PNR:" 22",
        Carrer: "none",
        TotalFare: "8888",
        Sold: "444",
        TimeLimit: "null",
    },
    {
        id: "2",
        Pax_Name: "@MUI",
        Contact: "0000020",
        PNR: "22",
        GSD_PNR:" 22",
        Carrer: "none",
        TotalFare: "8888",
        Sold: "444",
        TimeLimit: "null",
    },
    {
        id: "3",
        Pax_Name: "@MUI",
        Contact: "0000020",
        PNR: "22",
        GSD_PNR:" 22",
        Carrer: "none",
        TotalFare: "8888",
        Sold: "444",
        TimeLimit: "null",
    },
    {
        id: "4",
        Pax_Name: "@MUI",
        Contact: "0000020",
        PNR: "22",
        GSD_PNR:" 22",
        Carrer: "none",
        TotalFare: "8888",
        Sold: "444",
        TimeLimit: "null",
    },
    {
        id: "5",
        Pax_Name: "@MUI",
        Contact: "0000020",
        PNR: "22",
        GSD_PNR:" 22",
        Carrer: "none",
        TotalFare: "8888",
        Sold: "444",
        TimeLimit: "null",
    },
    {
        id: "6",
        Pax_Name: "@MUI",
        Contact: "0000020",
        PNR: "22",
        GSD_PNR:" 22",
        Carrer: "none",
        TotalFare: "8888",
        Sold: "444",
        TimeLimit: "null",
    }

]
export default oRows ;